import os
import json
from google import genai
from dotenv import load_dotenv

load_dotenv()

def _get_client():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY is not set. Create a .env file or set the environment variable before running.")
    return genai.Client(api_key=api_key)

def _get_model_cascade():
    """
    Returns the robust cascading model fallback order based on user preferences.
    Tries the .env file value first, then systematically downgrades to protect uptime.
    """
    env_model = os.getenv('GEMINI_MODEL', 'gemini-3.5-flash')
    return [
        env_model,                # Tier 1: User choice (e.g. gemini-3.5-flash)
        "gemini-3.5-flash-lite",  # Tier 2: Cost & speed optimized fallback
        "gemini-3.0-flash"        # Tier 3: High-capacity universal backup fallback
    ]

class ContentBrain:
    def get_trending_topic(self):
        """
        In a full build, this would scrape Google Trends or Twitter.
        For now, we ask Gemini to pick a viral niche topic using a model fallback loop.
        """
        prompts = "Give me 1 specific, viral, and engaging topic for a Short Documentary. It should be a 'Engaging Did you know' fact or a 'Fun/intriguing Engaging News'. return ONLY the topic name."
        client = _get_client()
        models_to_try = _get_model_cascade()
        
        for model_name in models_to_try:
            try:
                print(f"🤖 Attempting topic selection with {model_name}...")
                response = client.models.generate_content(
                    model=model_name, 
                    contents=prompts
                )
                topic = response.text.strip()
                print(f"🎯 Selected Topic: {topic} (Generated by {model_name})")
                return topic
            except Exception as e:
                print(f"⚠️ {model_name} failed during topic selection: {str(e)}")
                print("🔄 Falling back to the next model in the chain...")
                continue
                
        raise RuntimeError("❌ [Critical Error] All Gemini models in the pipeline failed to fetch a trending topic.")

    def generate_script(self, topic):
        """
        Generates a structured JSON script with visual cues using model fallback loops.
        """
        print(f"📝 Preparing to write script for: {topic}...")
        prompt = f"""
    You are the lead scriptwriter for a high-retention "Edutainment" YouTube Shorts channel.
    Topic: {topic}

    ### GOAL:
    Create a script where every sentence has a "Visual Switch". 
    To keep retention high, we need TWO different stock videos for every single scene.

    ### 1. SCRIPT REQUIREMENTS (The Voiceover):
    - **Perspective:** Strictly **3rd Person** ("Scientists found...", "The ocean hides...").
    - **Tone:** Engaging, fast-paced, logical. No fluff.
    - **Structure:** 8-9 Scenes total.
    - **Flow:** Hook -> Context -> Mechanism (How it works) -> Twist -> Outro.

    ### 2. VISUAL REQUIREMENTS (Dual Visuals):
    - For EVERY scene, provide TWO distinct search terms:
      - **visual_1:** Matches the *start* of the sentence.
      - **visual_2:** Matches the *end* of the sentence or provides a reaction/context.
    - **Strictly Literal:** If the text is "The economy crashed," do NOT search "sad man". Search "Stock market red chart".

    ### OUTPUT FORMAT (Strict JSON):
    [
        {{
            "id": 1,
            "text": "In 1995, fourteen wolves were released into Yellowstone Park, and they changed the rivers.",
            "visual_1": "wolves running snow aerial",
            "visual_2": "river flowing forest drone",
            "mood": "intriguing" 
        }},
        {{
            "id": 2,
            "text": "It sounds impossible, but the biology is actually simple math.",
            "visual_1": "person shocked looking at camera",
            "visual_2": "blackboard math equations chalk",
            "mood": "educational"
        }}
    ]
    """
        client = _get_client()
        models_to_try = _get_model_cascade()
        
        for model_name in models_to_try:
            try:
                print(f"🤖 Attempting script generation with {model_name}...")
                response = client.models.generate_content(
                    model=model_name, 
                    contents=prompt
                )
                
                # Clean the response to ensure it's valid JSON (sometimes AI adds markdown)
                clean_text = response.text.replace('```json', '').replace('```', '').strip()
                
                script_data = json.loads(clean_text)
                print(f"✨ Successfully generated and parsed script using {model_name}!")
                return script_data
                
            except json.JSONDecodeError:
                print(f"❌ JSON parsing failed for model output from {model_name}.")
                print("🔄 Falling back to the next model to attempt a cleaner format...")
                continue
            except Exception as e:
                print(f"⚠️ {model_name} failed during script generation: {str(e)}")
                print("🔄 Falling back to the next model in the chain...")
                continue
                
        raise RuntimeError("❌ [Critical Error] All Gemini models failed to generate a parseable video script.")
        
# --- TESTING THE MODULE ---
if __name__ == "__main__":
    brain = ContentBrain()
    try:
        topic = brain.get_trending_topic()
        script = brain.generate_script(topic)
        
        if script:
            # Save to file to verify
            with open("script.json", "w") as f:
                json.dump(script, f, indent=4)
                print("✅ Script saved to script.json")
    except Exception as error:
        print(f"💥 Pipeline Execution Crashed: {str(error)}")
